name: Build and Deploy to Cloud Run
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ror-deployment

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ror-deployment
          workload_identity_provider: "projects/260257811964/locations/global/workloadIdentityPools/github-pool/providers/github-actions"
          service_account: "github-gcp-credentials@ror-deployment.iam.gserviceaccount.com"

    #  - name: Set up Google Cloud SDK
     #   uses: google-github-actions/setup-gcloud@v2

      - name: Verify Active Account
        run: |
          gcloud auth list
          gcloud config list account
      
      - name: Configure Docker with Google Cloud auth
        run: |
          gcloud auth configure-docker

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u nabeehadev --password-stdin

      - name: Build Docker image
        run: |
          docker build -t nabeehadev/rorapp:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push nabeehadev/rorapp:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy rorapp \
            --image docker.io/nabeehadev/rorapp:latest \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated \
            --update-env-vars BUCKET_NAME=ror-deployment-gcp,DB_CONNECTION_NAME=ror-deployment:asia-south1:ror-database-gcp
